import type { Metadata } from "next";
import { Geist, Geist_Mono, Baloo_2, Anton, Poppins, Give_You_Glory } from "next/font/google";
import "./globals.css";
import SmoothScrollProvider from "@/src/@lib/smoothScrollProvider";
import { ReduxProvider } from "@/redux/reduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const baloo = Baloo_2({
  variable: "--font-baloo",
  subsets: ["latin"],
});
const scriptFont = Give_You_Glory({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-script",
});
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});
const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${scriptFont.variable} ${poppins.variable} ${anton.variable} ${geistMono.variable} ${baloo.variable} h-full antialiased`}
    >
      <ReduxProvider>
        <body className="min-h-full flex flex-col">
          <SmoothScrollProvider>{children}</SmoothScrollProvider></body>
      </ReduxProvider>
    </html >
  );
}
